services:
    api : 
      image : menashi/fastapi
      depends_on:
        - postgresql
      ports:
        - "80:8000"
      #volumes:
      #  - ./:/usr/src/app
      #command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
      # env_file:
      #   - ./.env
      environment:
        - DATABASE_HOSTNAME=${DATABASE_HOSTNAME}
        - DATABASE_PORT=${DATABASE_PORT}
        - DATABASE_NAME=${DATABASE_NAME}
        - DATABASE_USERNAME=${DATABASE_USERNAME}
        - DATABASE_PASSWORD=${DATABASE_PASSWORD}
        - SECRET_KEY=${SECRET_KEY}
        - ALGORITHM=${ALGORITHM}
        - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
    postgresql:
       image: postgres:15.4-alpine
       restart: always
       environment:
         - POSTGRES_USER=${DATABASE_USERNAME}
         - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
         - POSTGRES_DB=${DATABASE_NAME}
       volumes:
         - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
      
