"""adding phone number column

Revision ID: e9c324e4c3f4
Revises: 2e063654385f
Create Date: 2025-08-05 19:27:10.682620

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9c324e4c3f4'
down_revision: Union[str, Sequence[str], None] = '2e063654385f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Posts', sa.Column('phone_number', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Posts', 'phone_number')
    # ### end Alembic commands ###
