name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
   runs-on: ubuntu-latest
   steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: Installing Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.9' 
      - name: upgrade pip
        run: python -m pip install --upgrade pip
      - name: Installing all dependencies
        run: pip install -r requirements.txt